### PR TITLE
Check for non-existent etcd data directory when trying to fix permissions for its files

### LINKED ISSUE #53: [BUG] Runtime error when wrapper is run with Druid without Backups
**Describe the bug:**
When Druid is run with No Backups, I've observed that the wrapper process goes into Runtime error, more specifically a Segmentation fault. 

The PR #51 which was aimed at fixing data directory file permissions seems to have unintentionally caused this issue. 

<summary>See the logs</summary>
<details>
  
```
{"level":"info","ts":"2025-05-09T11:21:59.263Z","caller":"etcd-wrapper/main.go:67","msg":"Running with flags: backup-restore-ca-cert-bundle-path: , backup-restore-host-port: etcd-test-local:8080, backup-restore-tls-enabled: false, etcd-client-cert-path: , etcd-client-key-path: , etcd-ready-timeout: 0s, etcd-server-name: etcd-test-local"}
{"level":"info","ts":"2025-05-09T11:21:59.263Z","caller":"app/app.go:40","msg":"Initializing application","config":{"BackupRestore":{"HostPort":"etcd-test-local:8080","TLSEnabled":false,"CaCertBundlePath":""},"EtcdClientTLS":{"ServerName":"etcd-test-local","CertPath":"","KeyPath":""}}}
{"level":"error","ts":"2025-05-09T11:21:59.264Z","caller":"bootstrap/bootstrap.go:66","msg":"error while fetching initialization status","error":"Get \"http://etcd-test-local:8080/initialization/status\": dial tcp 127.0.0.1:8080: connect: connection refused","stacktrace":"github.com/gardener/etcd-wrapper/internal/bootstrap.(*initializer).Run\n\t/go/src/github.com/gardener/etcd-wrapper/internal/bootstrap/bootstrap.go:66\ngithub.com/gardener/etcd-wrapper/internal/app.(*Application).Setup\n\t/go/src/github.com/gardener/etcd-wrapper/internal/app/app.go:58\ngithub.com/gardener/etcd-wrapper/cmd.InitAndStartEtcd\n\t/go/src/github.com/gardener/etcd-wrapper/cmd/etcd.go:66\nmain.main\n\t/go/src/github.com/gardener/etcd-wrapper/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:283"}
{"level":"info","ts":"2025-05-09T11:21:59.264Z","caller":"bootstrap/bootstrap.go:68","msg":"Fetched initialization status","Status":"Unknown"}
{"level":"info","ts":"2025-05-09T11:22:00.267Z","caller":"bootstrap/bootstrap.go:68","msg":"Fetched initialization status","Status":"New"}
{"level":"error","ts":"2025-05-09T11:22:00.267Z","caller":"bootstrap/bootstrap.go:150","msg":"error in checking if exitCodeFile exists, assuming full-validation to be done.","exitCodeFilePath":"/var/etcd/data/exit_code","error":"stat /var/etcd/data/exit_code: no such file or directory","stacktrace":"github.com/gardener/etcd-wrapper/internal/bootstrap.determineValidationMode\n\t/go/src/github.com/gardener/etcd-wrapper/internal/bootstrap/bootstrap.go:150\ngithub.com/gardener/etcd-wrapper/internal/bootstrap.(*initializer).Run\n\t/go/src/github.com/gardener/etcd-wrapper/internal/bootstrap/bootstrap.go:70\ngithub.com/gardener/etcd-wrapper/internal/app.(*Application).Setup\n\t/go/src/github.com/gardener/etcd-wrapper/internal/app/app.go:58\ngithub.com/gardener/etcd-wrapper/cmd.InitAndStartEtcd\n\t/go/src/github.com/gardener/etcd-wrapper/cmd/etcd.go:66\nmain.main\n\t/go/src/github.com/gardener/etcd-wrapper/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:283"}
{"level":"info","ts":"2025-05-09T11:22:00.267Z","caller":"bootstrap/bootstrap.go:71","msg":"Fetched initialization status is `New`. Triggering etcd initialization with validation mode","mode":"full"}
{"level":"info","ts":"2025-05-09T11:22:01.269Z","caller":"bootstrap/bootstrap.go:68","msg":"Fetched initialization status","Status":"Successful"}
{"level":"info","ts":"2025-05-09T11:22:02.270Z","caller":"bootstrap/bootstrap.go:82","msg":"Etcd initialization succeeded"}
{"level":"info","ts":"2025-05-09T11:22:09.320Z","caller":"bootstrap/bootstrap.go:126","msg":"Fetched and written etcd configuration","path":"/home/nonroot/etcd.conf.yaml"}
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2025-05-09 11:22:09.321834 W | embed: Running http and grpc server on single port. This is not recommended for production.
{"level":"info","ts":"2025-05-09T11:22:09.323Z","caller":"app/readycheck.go:116","msg":"Starting HTTP server at addr","Port No: ":9095}
{"level":"warn","ts":"2025-05-09T11:22:09.324Z","caller":"clientv3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x4000141680/etcd-test-local:2379","attempt":0,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d84f8]

goroutine 1 [running]:
net/http.(*Server).Close(0x147e970?)
    /usr/local/go/src/net/http/server.go:3091 +0x28
github.com/gardener/etcd-wrapper/internal/app.(*Application).stopHTTPServer(...)
    /go/src/github.com/gardener/etcd-wrapper/internal/app/readycheck.go:139
github.com/gardener/etcd-wrapper/internal/app.(*Application).Start.func1()
    /go/src/github.com/gardener/etcd-wrapper/internal/app/app.go:86 +0x2c
github.com/gardener/etcd-wrapper/internal/app.(*Application).Start(0x40001d0000)
    /go/src/github.com/gardener/etcd-wrapper/internal/app/app.go:96 +0x1bc
github.com/gardener/etcd-wrapper/cmd.InitAndStartEtcd({0xd33418?, 0x400051b2c0?}, 0xc055d8?, 0xbb9498?)
    /go/src/github.com/gardener/etcd-wrapper/cmd/etcd.go:69 +0xb4
main.main()
    /go/src/github.com/gardener/etcd-wrapper/main.go:47 +0x2a4
stream closed EOF for default/etcd-test-0 (etcd)
```
</details>

**Expected behavior:**
It should work alike with Backups Enabled and Backups disabled. The runtime error should not happen.

**How To Reproduce (as minimally and precisely as possible):**

Please try running Druid with the below mentioned component versions and observe the `etcd` container logs.

**Environment (please complete the following information):**
 - Etcd wrapper version/commit ID : [used the PR commit](https://github.com/gardener/etcd-wrapper/commit/653fb7b2ab67b27446fe0b3d92e03e617f951ab5)
 - Etcd-druid version/commit ID : [Commit details](https://github.com/gardener/etcd-druid/commit/dfb0fbd555de0216b590c649c0eea94d18b2d2b9)
- Etcdbr version: [Commit details](https://github.com/gardener/etcd-backup-restore/commit/3e2d5518963195105e19490a7486cbed6db1cc65)
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]: NA

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
**How to categorize this PR?**

/area control-plane security
/kind bug

**What this PR does / why we need it**:
Check for non-existent etcd data directory when trying to fix permissions for files in it. This fixes a regression caused by #51 .

**Which issue(s) this PR fixes**:
Fixes #53 

**Special notes for your reviewer**:
/invite @anveshreddy18 @seshachalam-yv 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by anveshreddy18** [comment]
Thanks for the quick fix by raising PR @shreyas-s-rao, can you also add the unit tests for `ChangeFilePermissions` function.

File: internal/bootstrap/bootstrap.go [hunk 1]
```diff
@@ -85,14 +86,29 @@ func (i *initializer) Run(ctx context.Context) (*embed.Config, error) {
 
 // ChangeFilePermissions changes the file permissions of all files in the given directory and its subdirectories recursively.
 func ChangeFilePermissions(dir string, mode os.FileMode) error {
+	info, err := os.Stat(dir)
+	if err != nil {
+		if errors.Is(err, os.ErrNotExist) {
+			return nil
+		}
+		return fmt.Errorf("error stating directory %s: %v", dir, err)
```
Comment (anveshreddy18) [inline internal/bootstrap/bootstrap.go:94]:
```suggestion
		return fmt.Errorf("error stating directory %s: %w", dir, err)
```
Wrapping the returned error seems more appropriate here. Also because this returned error is wrapped with another error in the caller, so it may become inconsistent if we wrap one but not other in the tree.

File: internal/bootstrap/bootstrap.go [hunk 2]
```diff
@@ -85,14 +86,29 @@ func (i *initializer) Run(ctx context.Context) (*embed.Config, error) {
...
+	}
+
+	if !info.IsDir() {
+		return fmt.Errorf("path %s is not a directory", dir)
+	}
+
 	return filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
 		if err != nil {
-			return err
+			return fmt.Errorf("error walking the path %q: %v", path, err)
```
Comment (anveshreddy18) [inline internal/bootstrap/bootstrap.go:103]:
```suggestion
			return fmt.Errorf("error walking the path %q: %w", path, err)
```
same as above.

File: internal/bootstrap/bootstrap.go [hunk 3]
```diff
@@ -85,14 +86,29 @@ func (i *initializer) Run(ctx context.Context) (*embed.Config, error) {
...
 		}
 		if d.IsDir() {
 			return nil
 		}
-		return os.Chmod(path, mode)
+		if err = os.Chmod(path, mode); err != nil {
+			return fmt.Errorf("error changing file permissions for %q: %v", path, err)
```
Comment (anveshreddy18) [inline internal/bootstrap/bootstrap.go:109]:
```suggestion
			return fmt.Errorf("error changing file permissions for %q: %w", path, err)
```
same as above.

**Review by seshachalam-yv — APPROVED** [review]
/lgtm

**Review by anveshreddy18 — COMMENTED** [review]
PR looks good, just have couple of nits, PTAL. Thanks

**Comment by shreyas-s-rao** [comment]
@anveshreddy18 thanks. Addressed your comments. PTAL

**Review by anveshreddy18 — APPROVED** [review]
Thanks @shreyas-s-rao for addressing. 
LGTM
